### ISSUE TITLE
Missing required expression comparators

### ISSUE THREAD

**Issue by cgrisdale** [bcgsc/pori_ipr_python#34]
When running pori ipr python adapter using expression data as input I receive the following error:

Traceback (most recent call last):
  File "/projects/cgrisdale_prj/POG/GraphKB/PORI_python_adapter/pori_ipr_python/venv/bin/ipr", line 11, in <module>
    load_entry_point('ipr', 'console_scripts', 'ipr')()
  File "/projects/cgrisdale_prj/POG/GraphKB/PORI_python_adapter/pori_ipr_python/ipr/main.py", line 133, in command_interface
    generate_therapeutics=args.therapeutics,
  File "/projects/cgrisdale_prj/POG/GraphKB/PORI_python_adapter/pori_ipr_python/ipr/main.py", line 219, in create_report
    check_comparators(optional_content or {}, expression_variants)
  File "/projects/cgrisdale_prj/POG/GraphKB/PORI_python_adapter/pori_ipr_python/ipr/inputs.py", line 551, in check_comparators
    raise ValueError(f'missing required comparator definitions ({missing})')
ValueError: missing required comparator definitions (expression (biopsy site); expression (disease); expression (primary site))

Command:
ipr --username 'cgrisdale' --password 'myPass' -e tests/test_data/expression.tab --patient_id 'ExpTest02' -d 'colorectal cancer' -o ./ExpTest02_output.json

OS: centos7
Python: 3.6.9

**Comment by creisle** [comment]
What is happening here is that if your expression data contains percentiles, kiqr etc. We expect the JSON to define the corresponding comparators. This should be more obvious in the upcoming release where all content is passed via the JSON object
